default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres1
  password: '1234'
 
development:
  <<: *default
  database: oaktree_cms

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>